SpellsList["frost bolt"] = {
	name : "Frost Bolt",
	nameShort : "Frost Bolt",
	nameAlt : "Frost Bolt",
	classes : ["artificer", "druid", "sorcerer", "warlock", "wizard"],
	source : ["HB"],
	ritual : false,
	level : 0,
	school : "Conj",
	time : "1 a",
	range : "self",
	components : "S, M*",
	compMaterial : "a ranged weapon that has the ammo property & is worth at least 1sp",
	duration : "1 round",
	firstCol : "atwill",
	description : "create an icicle piece of ammo, on hit target takes weapon dmg and speed is reduced by 10ft. 5th lvl 1d6 cold dmg, add 1d6 at lvls 11th & 17th",
	descriptionMetric : "create an icicle piece of ammo, on hit target takes weapon dmg and speed is reduced by 10ft. 5th lvl 1d6 cold dmg, add 1d6 at lvls 11th & 17th",
	descriptionFull : desc([
		"You conjure and icicle, which is loaded and shot from the weapon used in this spell's casting. Make a ranged weapon attack against one creature within the weapon's normal range. On a hit, the target suffers the weapon attack's normal effects and then becomes wreathed in frost. The target's speed is reduced by 10ft until hte start of your next turn.",
		"At 5th level, the ranged weapon attack deals an extra 1d6 cold damage to the target on a hit. This damage increases by 1d6 when you reach 11th level (2d4), and 17th level (3d4).",
	]),
}
WeaponsList["frost bolt"] = {
	name : "Frost Bolt",
    regExpSearch : /^(?=.*frost)(?=.*bolt).*$/i,
	source : ["HB"],
	list : "spell",
	ability : 6,
    abilitytodamage : true,
	type : "Cantrip",
	damage : [1,6, "cold"],
	range : "weapon",
	description : "icicle ammo, reduce speed by 10ft, 5th 1d6, 11th 2d6, 17th 3d6.",
}