/*	-INFORMATION-
	Subject:	Magical Potions
	Effect:		Add common potions to the equipment list and magic item list
	Remarks:	This is to add the potions created by RPGPapercrafts & Raafling (https://www.drivethrurpg.com/product/241053/Magic-Potions--Ingredients)
	Coded by :	rayvenwilk
	Date :		09.22.2021
	Sheet:		v13.0.5
*/

var iFileName = "MagicalPotions by RPGPapercrafts(transcribed by rayvenwilk.js";

RequiredSheetVersion("13.0.5");

//Equipment list
GearList["potion, blimberry juice"] = {
        name : "Blimberry Juice",
        infoname : "Potion, Blimberry Juice",
        amount : 1,
        weight : 0.25,
        source : ["HB"],
},
GearList["potion, fey dew"] = {
	name : "Few Dew",
	infoname : "Potion, Few Dew",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, witch spoil"] = {
	name : "Witch Spoil",
	infoname : "Potion, Witch Spoil",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, assassin's tear"] = {
	name : "Assassin's Tear",
	infoname : "Potion, Assassin's Tear",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, Moonbrine"] = {
	name : "Moonbrine",
	infoname : "Potion, Moonbrine",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, witherbroth"] = {
	name : "Witherbroth",
	infoname : "Potion, Witherbroth",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, boarblood"] = {
	name : "Boarblood",
	infoname : "Potion, Boarblood",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, mountain brew"] = {
	name : "Mountain Brew",
	infoname : "Potion, Mountain Brew",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, thunderjuice"] = {
	name : "Thunderjuice",
	infoname : "Potion, Thunderjuice",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, deerblood"] = {
	name : "Deerblood",
	infoname : "Potion, Deerblood",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, brain milk"] = {
	name : "Brain Milk",
	infoname : "Potion, Brain Milk",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, owl sip"] = {
	name : "Owl Sip",
	infoname : "Potion, Owl Sip",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, quickling milk"] = {
	name : "Quickling Milk",
	infoname : "Potion, Quickling Milk",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, liquid lightning"] = {
	name : "Liquid Lightning",
	infoname : "Potion, Liquid Lightning",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, spirit swig"] = {
	name : "Spirit Swig",
	infoname : "Potion, Spirit Swig",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, waterlung"] = {
	name : "Waterlung",
	infoname : "Potion, Waterlung",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, faelixir"] = {
	name : "Faelixir",
	infoname : "Potion, Faelixir",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, shadowblend"] = {
	name : "Shadowblend",
	infoname : "Potion, Shadowblend",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, dwarven spirits"] = {
	name : "Dwarven Spirits",
	infoname : "Potion, Dwarven Spirits",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, ornate glue"] = {
	name : "Ornate Glue",
	infoname : "Potion, Ornate Glue",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, drifters juice"] = {
	name : "Drifters Juice",
	infoname : "Potion, Drifters Juice",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, phoenix blood"] = {
	name : "Phoenix Blood",
	infoname : "Potion, Phoenix Blood",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, demon balm"] = {
	name : "Demon Balm",
	infoname : "Potion, Demon Balm",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, masking broth"] = {
	name : "Masking Broth",
	infoname : "Potion, Masking Broth",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, bait broth"] = {
	name : "Bait Broth",
	infoname : "Potion, Bait Broth",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, stench broth"] = {
	name : "Stench Broth",
	infoname : "Potion, Stench Broth",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, chauntea's blessing"] = {
	name : "Chauntea's Blessing",
	infoname : "Potion, Chauntea's Blessing",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, chauntea's grace"] = {
	name : "Chauntea's Grace",
	infoname : "Potion, Chauntea's Grace",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},
GearList["potion, silvershot"] = {
	name : "Silvershot",
	infoname : "Potion, Silvershot",
	amount : 1,
	weight : 0.25,
	source : ["HB"],
},

//Magic Item List
MagicItemsList["blimberry juice"] = {
	name : "Blimberry Juice",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant 1d4 +2 health. Overconsumption can have a laxating effect.",
	descriptionFull : "Instant 1d4 +2 health. \nOverconsumption can have a laxating effect.",
},
MagicItemsList["fey dew"] = {
	name : "Fey Dew",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant 4d4 +8 health. What does it taste like? Pretty much like a fairy tickling your tongue.",
	descriptionFull : "Instant 4d4 +8 health. \nWhat does it taste like? Pretty much like a fairy tickling your tongue.",
},
MagicItemsList["witch spoil"] = {
	name : "Witch Spoil",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "After 10 min of consumption, consumer must succeed on a DC 10 Con save or take 1d6 +2 poison dmg and become poisoned. \nConsumer detects poison with passive Nature skill of 10.",
	descriptionFull : "After 10 min of consumption, consumer must succeed on a DC 10 Con save or take 1d6 +2 poison dmg and become poisoned. \nConsumer detects poison with passive Nature skill of 10.",
},
MagicItemsList["assassin's tear"] = {
	name : "Assassin's Tear",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer much succeed on a DC 14 Con saving throw or take 2d6 +4 poison dmg and become poisoned. \nConsumer detects poison with a Nature check or passive nature skill of 14",
	descriptionFull : "Instant, consumer much succeed on a DC 14 Con saving throw or take 2d6 +4 poison dmg and become poisoned. \nConsumer detects poison with a Nature check or passive nature skill of 14",
},
MagicItemsList["moonbrine"] = {
	name : "Moonbrine",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant 2d4 +4 health. \nStore in a dark place away from moonlight unless you want to explode.",
	descriptionFull : "Instant 2d4 +4 health. \nStore in a dark place away from moonlight unless you want to explode.",
},
MagicItemsList["witherbroth"] = {
	name : "Witherbroth",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer must succeed on a DC 20 Con saving throw or take 4d6 +8 poison dmg and become poisoned. \nConsumer detects poison with a Nature check or passive nature skill of 18.",
	descriptionFull : "Instant, consumer must succeed on a DC 20 Con saving throw or take 4d6 +8 poison dmg and become poisoned. \nConsumer detects poison with a Nature check or passive nature skill of 18.",
},
MagicItemsList["boarblood"] = {
	name : "Boarblood",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, Strength +1 (1hr), afterwards the consumer must succeed on a DC 10 Con saving throw or take 1 lvl of exhaustion. \nSomewhere in the process of this brew, a boar got hurt. It better be for very good reasons.",
	descriptionFull : "Instant, Strength +1 (1hr), afterwards the consumer must succeed on a DC 10 Con saving throw or take 1 lvl of exhaustion. \nSomewhere in the process of this brew, a boar got hurt. It better be for very good reasons.",
},
MagicItemsList["mountain brew"] = {
	name : "Mountain Brew",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, Strength +2 (1hr), aftwards the consumer must succeed on a DC 12 Con saving throw or take 2 lvls of exhaustion. \nDispite the name, you can't actually lift mountains. But you sure can move boulders.",
	descriptionFull : "Instant, Strength +2 (1hr), aftwards the consumer must succeed on a DC 12 Con saving throw or take 2 lvls of exhaustion. \nDispite the name, you can't actually lift mountains. But you sure can move boulders.",
},
MagicItemsList["thunderjuice"] = {
	name : "Thunderjuice",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, Strength +3 (1hr), afterwards the consumer must succeed on a DC 14 Con saving throw or take 3 lvls of exhaustion. \nWould you drink a holy brew blessed by some unknown deity? Know what you consume, stay safe.",
	descriptionFull : "Instant, Strength +3 (1hr), afterwards the consumer must succeed on a DC 14 Con saving throw or take 3 lvls of exhaustion. \nWould you drink a holy brew blessed by some unknown deity? Know what you consume, stay safe.",
},
MagicItemsList["deerblood"] = {
	name : "Deerblood",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, Dexterity +1 (1hr), afterwards the consumer must succeed on a DC 10 Con saving throw or take 1 lvl of exhaustion. \nSomewhere in the process of this brew, an innocent deer got hurt. I hope you can sleep tonight.",
	descriptionFull : "Instant, Dexterity +1 (1hr), afterwards the consumer must succeed on a DC 10 Con saving throw or take 1 lvl of exhaustion. \nSomewhere in the process of this brew, an innocent deer got hurt. I hope you can sleep tonight.",
},
MagicItemsList["brain milk"] = {
	name : "Brain Milk",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, adv. on Wisdom skill checks and saving throws (1hr), afterwards the consumer must succeed on a DC 12 Wis saving throw or suffer from a short-term madness effect. \nThe body can handle enhancements. The mind is not always so resilient.",
	descriptionFull : "Instant, adv. on Wisdom skill checks and saving throws (1hr), afterwards the consumer must succeed on a DC 12 Wis saving throw or suffer from a short-term madness effect. \nThe body can handle enhancements. The mind is not always so resilient.",
},
MagicItemsList["owl sip"] = {
	name : "Owl Sip",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, darkvision (1hr).\nAvoid looking into direct lightsources, it may blind you for a minute.",
	descriptionFull : "Instant, darkvision (1hr). \nAvoid looking into direct lightsources, it may blind you for a minute.",
},
MagicItemsList["quickling milk"] = {
	name : "Quickling Milk",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, Dexterity +2 (1hr), afterwards the consumer must succeed on a DC 10 Con saving throw or take 2 lvls of exhaustion. \nNo Quicklings have been milked. It's called this because Quicklings commonly drink it.",
	descriptionFull : "Instant, Dexterity +2 (1hr), afterwards the consumer must succeed on a DC 10 Con saving throw or take 2 lvls of exhaustion. \nNo Quicklings have been milked. It's called this because Quicklings commonly drink it.",
},
MagicItemsList["liquid lightning"] = {
	name : "Liquid Lightning",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, Dexterity +3 (1hr), afterwards the consumer must succeed on a DC 10 Con saving throw or take 3 lvls of exhaustion. \nDespite the name, you can't outrun lightning. Sorry.",
	descriptionFull : "Instant, Dexterity +3 (1hr), afterwards the consumer must succeed on a DC 10 Con saving throw or take 3 lvls of exhaustion. \nDespite the name, you can't outrun lightning. Sorry.",
},
MagicItemsList["spirit swig"] = {
	name : "Spirit Swig",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, ethereal vision for 1hr. \nBeware: what has been seen can not be unseen.",
	descriptionFull : "Instant, ethereal vision for 1hr. \nBeware: what has been seen can not be unseen.",
},
MagicItemsList["waterlung"] = {
	name : "Waterlung",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer breathes water instead of air (1hr). \nDo not combine with potions containing Frost-leaf, you will snap freeze your lungs. Avoid drinking the Atral Nightcap whilst underwater.",
	descriptionFull : "Instant, consumer breathes water instead of air (1hr). \nDo not combine with potions containing Frost-leaf, you will snap freeze your lungs. Avoid drinking the Atral Nightcap whilst underwater.",
},
MagicItemsList["faelixir"] = {
	name : "Faelixir",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer receives the effect of a faery fire spell (1hr). \nWhile under the effect of this potion, the healing properties of Fey Dew are doubled.",
	descriptionFull : "Instant, consumer receives the effect of a faery fire spell (1hr). \nWhile under the effect of this potion, the healing properties of Fey Dew are doubled.",
},
MagicItemsList["shadowblend"] = {
	name : "Shadowblend",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer and their wearables become invisible (1hr). \nThis effect will immediately end when used with potions that use Sunpetal Daisy or Sapphire Sali.",
	descriptionFull : "Instant, consumer and their wearables become invisible (1hr). \nThis effect will immediately end when used with potions that use Sunpetal Daisy or Sapphire Sali.",
},
MagicItemsList["dwarven spirits"] = {
	name : "Dwarven Spirits",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, poison resistance (1hr), afterwards the consumer must succeed on a DC 6 Con saving throw or become drunk and Stunned. \nOf course dwarves don't need this themselves. They made it to sell to you.",
	descriptionFull : "Instant, poison resistance (1hr), afterwards the consumer must succeed on a DC 6 Con saving throw or become drunk and Stunned. \nOf course dwarves don't need this themselves. They made it to sell to you.",
},
MagicItemsList["ornate glue"] = {
	name : "Ornate Glue",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Takes effect in 1 rnd or 6 seconds after applying. Full bottle glues 100 tiny, 10 small, or 1 medium object of any material together, which can be removed with a DC 14 Str check. \nDon't glue your fingers together.",
	descriptionFull : "Takes effect in 1 rnd or 6 seconds after applying. Full bottle glues 100 tiny, 10 small, or 1 medium object of any material together, which can be removed with a DC 14 Str check. \nDon't glue your fingers together.",
},
MagicItemsList["drifters juice"] = {
	name : "Drifters Juice",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer's body weight reduces to 1/10th of their original weight. Movement +10ft and +5 to Stealth, Athletics, and Acrobatics checks (1hr). \nDo not drink more than one of these at a time or your muscles will stop functioning.",
	descriptionFull : "Instant, consumer's body weight reduces to 1/10th of their original weight. Movement +10ft and +5 to Stealth, Athletics, and Acrobatics checks (1hr). \nDo not drink more than one of these at a time or your muscles will stop functioning.",
},
MagicItemsList["phoenix blood"] = {
	name : "Phoenix Blood",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, fire resistance (1hr). \nHumanoids may experience their skin turning red, horns growing from their heads and/or growing a tail when perpetually overconsumed.",
	descriptionFull : "Instant, fire resistance (1hr). \nHumanoids may experience their skin turning red, horns growing from their heads and/or growing a tail when perpetually overconsumed.",
},
MagicItemsList["demon balm"] = {
	name : "Demon Balm",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, a liquid balm that can be applied to a surface and ignited with a source of fire. One brew is enough to burn for 10hrs, or can be smudged over 10ft burning for 1hr. \nGreat as a light source, marking your path, or writing You're Next in flames on your rival's house.",
	descriptionFull : "Instant, a liquid balm that can be applied to a surface and ignited with a source of fire. One brew is enough to burn for 10hrs, or can be smudged over 10ft burning for 1hr. \nGreat as a light source, marking your path, or writing You're Next in flames on your rival's house.",
},
MagicItemsList["masking broth"] = {
	name : "Masking Broth",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, masks a scent or odor originating from a 5ft area, or medium/small creature. No other creatures can smell you (1hr). \nWe can still hear you farting, you know.",
	descriptionFull : "Instant, masks a scent or odor originating from a 5ft area, or medium/small creature. No other creatures can smell you (1hr). \nWe can still hear you farting, you know.",
},
MagicItemsList["bait broth"] = {
	name : "Bait Broth",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, gives off an irresistable scent in a 60ft area that attracts a specific beast or monstrosity (chosen at time of brewing). The affected creatures much succeed on a DC 12 Cha saving throw or be charmed and you gain Animal Handling +4 against this creature (1hr). \nBe careful how you use this. We discovered that elephants are very into cuddling and we can not recommend the experience.",
	descriptionFull : "Instant, gives off an irresistable scent in a 60ft area that attracts a specific beast or monstrosity (chosen at time of brewing). The affected creatures much succeed on a DC 12 Cha saving throw or be charmed and you gain Animal Handling +4 against this creature (1hr). \nBe careful how you use this. We discovered that elephants are very into cuddling and we can not recommend the experience.",
},
MagicItemsList["stench broth"] = {
	name : "Stench Broth",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, gives off a terrible scent in a 60ft area that repels a specific beast or monstrosity (chosen at time of brewing). The affected creatures much succeed on a DC 12 Cha saving throw or be frightened (1hr). \nPlease use far away from civilization. Also please don't scare wild animals towards civilization.",
	descriptionFull : "Instant, gives off a terrible scent in a 60ft area that repels a specific beast or monstrosity (chosen at time of brewing). The affected creatures much succeed on a DC 12 Cha saving throw or be frightened (1hr). \nPlease use far away from civilization. Also please don't scare wild animals towards civilization.",
},
MagicItemsList["chauntea's blessing"] = {
	name : "Chauntea's Blessing",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "4hrs after consumption, consumer receives the effects of a Remove Curse spell. \nThis recipe is impossibly simple. Spellcasters just can't accept it works.",
	descriptionFull : "4hrs after consumption, consumer receives the effects of a Remove Curse spell. \nThis recipe is impossibly simple. Spellcasters just can't accept it works.",
},
MagicItemsList["chauntea's grace"] = {
	name : "Chauntea's Grace",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer receives the effects of a Revivify spell as long as they have been dead no longer than 1 min, restores 1 HP. \nBe sure the creature has been dead less than a minute or an evil spirit may enter first.",
	descriptionFull : "Instant, consumer receives the effects of a Revivify spell as long as they have been dead no longer than 1 min, restores 1 HP. \nBe sure the creature has been dead less than a minute or an evil spirit may enter first.",
},
MagicItemsList["silvershot"] = {
	name : "Silvershot",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer receives the effects of a short rest and can spend their hit die but suffers 1 lvl of exhaustion every hour until a long rest. \nDrink 2 to get a long rest effect! Also get 1 permanent madness and 1 exhaustion level per minute.",
	descriptionFull : "Instant, consumer receives the effects of a short rest and can spend their hit die but suffers 1 lvl of exhaustion every hour until a long rest. \nDrink 2 to get a long rest effect! Also get 1 permanent madness and 1 exhaustion level per minute.",
},
MagicItemsList["astral nightcap"] = {
	name : "Astral Nightcap",
	source : ["HB"],
	type : "potion",
	rarity : "common",
	weight : 0.25,
	description : "Instant, consumer immediately falls asleep for 8hrs and can not be awakened. \nBe sure to have someone trustworty to watch over you.",
	descriptionFull : "Instant, consumer immediately falls asleep for 8hrs and can not be awakened. \nBe sure to have someone trustworty to watch over you.",
}